[package]
name = "pallet-evm-living-assets-ownership"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>", "Drew Stone <drew@commonwealth.im>"]
license = "Apache-2.0"
description = "Living assets ownership precompile"
repository = "https://github.com/freeverseio/pallet-livingassets-ownership"
edition = "2021"

[dependencies]
parity-scale-codec = { version = "3.2.2", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.0", default-features = false, features = [
	"derive",
] }

# Frontier
fp-evm = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.43", default-features = false }
pallet-evm = { git = "https://github.com/paritytech/frontier.git", branch = "polkadot-v0.9.43", default-features = false }

# Substrate
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }

# Local pallet
pallet-living-assets-ownership = { path = "../../pallets/living-assets-ownership", default-features = false }

# Utils
precompile-utils = { path = "../utils", default-features = false }
precompile-utils-macro = { path = "../utils/macro", default-features = false }

num_enum = { version = "0.5.3", default-features = false }

[features]
default = ["std"]
std = [
	# Frontier
	"fp-evm/std",
	"pallet-evm/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"pallet-living-assets-ownership/std",
	"num_enum/std",
	"frame-support/std",
	"sp-arithmetic/std",
	"precompile-utils/std",
	"parity-scale-codec/std",
	"scale-info/std",
]
