[relaychain]
default_command = "../../binaries/polkadot-v0.9.42"
default_args = [ "-lparachain=debug" ]
chain_spec_path = "./specs/rococo-freeverse-chainspec-local.json"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true
chain_spec_path = "./specs/arrakis-local.json"

  [parachains.collator]
  name = "ownership-collator-pandora"
  command = "../../binaries/parachain-template-node-pandora-arrakis"
  validator = true

[[parachains]]
id = 2002
cumulus_based = true
chain = "arrakis"

  [parachains.collator]
  name = "ownership-collator-sudo"
  command = "../../binaries/parachain-template-node-v0.0.4-dev-local"
