[relaychain]
default_command = "~/Documents/efinity/polkadot/target/release/polkadot"
default_args = [ "-lparachain=debug" ]
chain_spec_path = "./specs/rococo-freeverse-chainspec-local.json"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true
chain_spec_path = "./specs/arrakis-local.json"

  [parachains.collator]
  name = "ownership-collator-pandora"
  command = "./target/release/parachain-template-node"
  validator = true
