[relaychain]
default_command = "~/Documents/efinity/polkadot/target/release/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true
add_to_genesis = true
chain = "local"

  [[parachains.collators]]
  name = "alice"
  command = "./target/release/parachain-template-node"
  validator = true
  ws_port = 9910
  args = [""]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"