[relaychain]
default_command = "../binaries/polkadot-v0.9.42"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000
cumulus_based = true

  [parachains.collator]
  name = "ownership-collator"
  command = "../binaries/parachain-template-node"