[package]
name = "precompile-utils-macro"
authors = ["StakeTechnologies", "PureStake"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
num_enum = { version = "0.5.3", default-features = false }
proc-macro2 = "1.0"
quote = "1.0"
sha3 = { version = "0.10", default-features = false }
syn = { version = "1.0", features = ["extra-traits", "fold", "full", "visit"] }
