name: Publish

on:
  # Triggers the workflow on push events for tags only
  push:
    branches: [devops/new_image_every_push]
    tags:
      # Catches v1.2.3 and v1.2.3-rc1
      - v[0-9]+.[0-9]+.[0-9]+*
  # Triggger the workflow whenever the "Build" workflow completes
  workflow_run:
    workflows: [Build]
    types:
      - completed
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# Set an environment variable (that can be overriden) for the Docker Repo
env:
  DOCKER_REPO: freeverseio/laos-ownership-node

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    needs: build  
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repo
        uses: actions/checkout@v3      

      # Login to Docker hub using the credentials stored in the repository secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Download the binary from the previous workflow
      - name: Download x86_64 linux binary
        uses: actions/download-artifact@v3
        with:
          name: parachain-template-node
          path: ${{ github.workspace }}

      # Publish image version tag
      - name: Publish docker image using tag
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ github.ref_name }}
            ${{ env.DOCKER_REPO }}:latest
      # Publish image version sha
      - name: Publish docker image using commit sha
        if: startsWith(github.event.ref, 'refs/heads/')
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ github.ref_sha }}

